"""initial

Revision ID: 10a0ed9049de
Revises: 
Create Date: 2024-06-27 21:46:11.850179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10a0ed9049de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('devicename', sa.String(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('ssh_port', sa.Integer(), nullable=False),
    sa.Column('https_port', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_devicename'), ['devicename'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_hostname'), ['hostname'], unique=False)

    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('test_suite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=12), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('final', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_suite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_suite_name'), ['name'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=140), nullable=True),
    sa.Column('about_me', sa.String(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('page_size', sa.Integer(), nullable=True),
    sa.Column('admin', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('device_validation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('suite_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('submitted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('approved', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('final', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['suite_id'], ['test_suite.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_validation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_validation_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_validation_suite_id'), ['suite_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_validation_timestamp'), ['timestamp'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    op.create_table('task',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('complete', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_name'), ['name'], unique=False)

    op.create_table('test_case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=12), nullable=True),
    sa.Column('function', sa.String(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('approver_role_id', sa.Integer(), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['approver_role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_case', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_case_name'), ['name'], unique=False)

    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('validation_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_override', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('force_failure', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['validation_id'], ['device_validation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_sequence'), ['sequence'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_validation_id'), ['validation_id'], unique=False)

    op.create_table('suite_case',
    sa.Column('suite_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['test_case.id'], ),
    sa.ForeignKeyConstraint(['suite_id'], ['test_suite.id'], ),
    sa.PrimaryKeyConstraint('suite_id', 'case_id')
    )
    with op.batch_alter_table('suite_case', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suite_case_sequence'), ['sequence'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suite_case', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suite_case_sequence'))

    op.drop_table('suite_case')
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_validation_id'))
        batch_op.drop_index(batch_op.f('ix_comment_user_id'))
        batch_op.drop_index(batch_op.f('ix_comment_timestamp'))
        batch_op.drop_index(batch_op.f('ix_comment_sequence'))

    op.drop_table('comment')
    op.drop_table('user_role')
    with op.batch_alter_table('test_case', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_case_name'))

    op.drop_table('test_case')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_name'))

    op.drop_table('task')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_timestamp'))
        batch_op.drop_index(batch_op.f('ix_notification_name'))

    op.drop_table('notification')
    with op.batch_alter_table('device_validation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_validation_timestamp'))
        batch_op.drop_index(batch_op.f('ix_device_validation_suite_id'))
        batch_op.drop_index(batch_op.f('ix_device_validation_device_id'))

    op.drop_table('device_validation')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_token'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('test_suite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_suite_name'))

    op.drop_table('test_suite')
    op.drop_table('role')
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_hostname'))
        batch_op.drop_index(batch_op.f('ix_device_devicename'))

    op.drop_table('device')
    # ### end Alembic commands ###
