"""add requirement description for TestCase

Revision ID: 3427f97a9327
Revises: 048a8722153b
Create Date: 2024-07-05 15:32:49.061540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3427f97a9327'
down_revision = '048a8722153b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_case', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
