"""SuiteCase troubles

Revision ID: 5f9b5e7304d7
Revises: 10a0ed9049de
Create Date: 2024-06-27 22:29:32.820521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9b5e7304d7'
down_revision = '10a0ed9049de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suite_case', schema=None) as batch_op:
        batch_op.alter_column('sequence',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suite_case', schema=None) as batch_op:
        batch_op.alter_column('sequence',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
