"""TestSuite has final lock

Revision ID: 85959a4a4a45
Revises: 8a8e85050b7e
Create Date: 2024-06-27 13:35:34.758942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85959a4a4a45'
down_revision = '8a8e85050b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_suite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final', sa.Boolean(), default=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_suite', schema=None) as batch_op:
        batch_op.drop_column('final')

    # ### end Alembic commands ###
