"""fix default=False

Revision ID: 8b017e8c74a6
Revises: 85959a4a4a45
Create Date: 2024-06-27 20:02:53.932146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b017e8c74a6'
down_revision = '85959a4a4a45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_suite', schema=None) as batch_op:
        batch_op.alter_column('final',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_suite', schema=None) as batch_op:
        batch_op.alter_column('final',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
