"""name/version uniqueconstraint for TestCase and TestSuite

Revision ID: a71785c03bac
Revises: 3427f97a9327
Create Date: 2024-07-08 21:38:57.764107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a71785c03bac'
down_revision = '3427f97a9327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_case', schema=None) as batch_op:
        batch_op.create_unique_constraint('_name_version_uc', ['name', 'version'])

    with op.batch_alter_table('test_suite', schema=None) as batch_op:
        batch_op.create_unique_constraint('_name_version_uc', ['name', 'version'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_suite', schema=None) as batch_op:
        batch_op.drop_constraint('_name_version_uc', type_='unique')

    with op.batch_alter_table('test_case', schema=None) as batch_op:
        batch_op.drop_constraint('_name_version_uc', type_='unique')

    # ### end Alembic commands ###
